# Los valores de projectKey y organization se pasan como secrets desde el pipeline
# sonar.organization y sonar.projectKey se inyectan via -Dsonar args en el workflow

sonar.projectName=AS241S5 - Frontend Angular

# Fuentes a analizar
sonar.sources=my-app/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/coverage/**,my-app/.angular/**

# TypeScript
sonar.typescript.tsconfigPath=my-app/tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
